services:
  nginx:
    image: nginx:alpine
    container_name: dhcp-test-nginx
    networks:
      - dhcp-net
  caddy:
    image: caddy:alpine
    container_name: dhcp-test-caddy
    networks:
      - dhcp-net

networks:
  dhcp-net:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      driver: fox.zoo.twofactor.space/tuzi/docker-dhcp-ipam-plugin:latest
      config:
        - subnet: "10.0.0.0/15"
          gateway: "10.0.0.1"
