services:
  nginx:
    image: nginx:alpine
    networks:
      - dhcp-net
  caddy:
    image: caddy:alpine
    networks:
      - dhcp-net

networks:
  dhcp-net:
    driver: macvlan
    enable_ipv6: true
    driver_opts:
      parent: ens18
    ipam:
      driver: ghcr.io/zhisana/docker-dhcp-ipam-plugin:latest
      config:
        - subnet: "10.0.0.0/15"
          gateway: "10.0.0.1"
          # ip_range: "10.0.0.0/24"
        - subnet: "2409:8a50:a70:2110::/64"
          gateway: "2409:8a50:a70:2110::1"
