services:
  nginx:
    image: nginx:alpine
    networks:
      - macvlan-with-dhcp
  caddy:
    image: caddy:alpine
    networks:
      - macvlan-with-dhcp

networks:
  macvlan-with-dhcp:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      driver: fox.zoo.twofactor.space/tuzi/docker-dhcp-ipam-plugin:latest
      config:
        - subnet: "10.0.0.0/15"
          gateway: "10.0.0.1"
          # ip_range: "10.0.0.0/24"
